#pragma once

namespace Jde::Markets::TwsWebSocket
{
	enum class EWebReceive : short
	{
		None									= 0,
		RequestMarketData             = 1,
		CANCEL_MKT_DATA               = 2,
		PlaceOrder                    = 3,
		CancelOrder                   = 4,
		REQ_OPEN_ORDERS               = 5,
		REQ_ACCT_DATA                 = 6,
		REQ_EXECUTIONS                = 7,
		RequestIds                    = 8,
		REQ_CONTRACT_DATA             = 9,
		REQ_MKT_DEPTH                 = 10,
		CANCEL_MKT_DEPTH              = 11,
		REQ_NEWS_BULLETINS            = 12,
		CANCEL_NEWS_BULLETINS         = 13,
		SET_SERVER_LOGLEVEL           = 14,
		REQ_AUTO_OPEN_ORDERS          = 15,
		REQ_ALL_OPEN_ORDERS           = 16,
		ReqManagedAccounts	         = 17,
		REQ_FA                        = 18,
		REPLACE_FA                    = 19,
		REQ_HISTORICAL_DATA           = 20,
		EXERCISE_OPTIONS              = 21,
		REQ_SCANNER_SUBSCRIPTION      = 22,
		CANCEL_SCANNER_SUBSCRIPTION   = 23,
		REQ_SCANNER_PARAMETERS        = 24,
		CANCEL_HISTORICAL_DATA        = 25,
		CurrentTime                   = 49,
		RequestRealTimeBars           = 50,
		CANCEL_REAL_TIME_BARS         = 51,
		REQ_FUNDAMENTAL_DATA          = 52,
		CANCEL_FUNDAMENTAL_DATA       = 53,
		REQ_CALC_IMPLIED_VOLAT        = 54,
		REQ_CALC_OPTION_PRICE         = 55,
		CANCEL_CALC_IMPLIED_VOLAT     = 56,
		CANCEL_CALC_OPTION_PRICE      = 57,
		REQ_GLOBAL_CANCEL             = 58,
		REQ_MARKET_DATA_TYPE          = 59,
		RequestPositions              = 61,
		REQ_ACCOUNT_SUMMARY           = 62,
		CANCEL_ACCOUNT_SUMMARY        = 63,
		CancelPositions              = 64,
		VERIFY_REQUEST                = 65,
		VERIFY_MESSAGE                = 66,
		QUERY_DISPLAY_GROUPS          = 67,
		SUBSCRIBE_TO_GROUP_EVENTS     = 68,
		UPDATE_DISPLAY_GROUP          = 69,
		UNSUBSCRIBE_FROM_GROUP_EVENTS = 70,
		StartApi                      = 71,
		VERIFY_AND_AUTH_REQUEST       = 72,
		VERIFY_AND_AUTH_MESSAGE       = 73,
		REQ_POSITIONS_MULTI           = 74,
		CANCEL_POSITIONS_MULTI        = 75,
		RequestAccountUpdatesMulti    = 76,
		CANCEL_ACCOUNT_UPDATES_MULTI  = 77,
		REQ_SEC_DEF_OPT_PARAMS        = 78,
		REQ_SOFT_DOLLAR_TIERS         = 79,
		REQ_FAMILY_CODES              = 80,
		REQ_MATCHING_SYMBOLS          = 81,
		REQ_MKT_DEPTH_EXCHANGES       = 82,
		REQ_SMART_COMPONENTS          = 83,
		REQ_NEWS_ARTICLE              = 84,
		REQ_NEWS_PROVIDERS            = 85,
		REQ_HISTORICAL_NEWS           = 86,
		REQ_HEAD_TIMESTAMP            = 87,
		REQ_HISTOGRAM_DATA            = 88,
		CANCEL_HISTOGRAM_DATA         = 89,
		CANCEL_HEAD_TIMESTAMP         = 90,
		REQ_MARKET_RULE               = 91,
		REQ_PNL                       = 92,
		CANCEL_PNL                    = 93,
		REQ_PNL_SINGLE                = 94,
		CANCEL_PNL_SINGLE             = 95,
		REQ_HISTORICAL_TICKS          = 96,
		REQ_TICK_BY_TICK_DATA         = 97,
		CANCEL_TICK_BY_TICK_DATA      = 98
	};

	constexpr sv EWebReceiveStrings[]=
	{
		"None",
		"RequestMarketData",
		"CANCEL_MKT_DATA",
		"PlaceOrder",
		"CancelOrder",
		"REQ_OPEN_ORDERS",
		"REQ_ACCT_DATA",
		"REQ_EXECUTIONS",
		"RequestIds",
		"REQ_CONTRACT_DATA",
		"REQ_MKT_DEPTH",
		"CANCEL_MKT_DEPTH",
		"REQ_NEWS_BULLETINS",
		"CANCEL_NEWS_BULLETINS",
		"SET_SERVER_LOGLEVEL",
		"REQ_AUTO_OPEN_ORDERS",
		"REQ_ALL_OPEN_ORDERS",
		"REQ_MANAGED_ACCTS",
		"REQ_FA",
		"REPLACE_FA",
		"REQ_HISTORICAL_DATA",
		"EXERCISE_OPTIONS",
		"REQ_SCANNER_SUBSCRIPTION",
		"CANCEL_SCANNER_SUBSCRIPTION",
		"REQ_SCANNER_PARAMETERS",
		"CANCEL_HISTORICAL_DATA",
		"26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48",
		"CurrentTime",
		"RequestRealTimeBars",
		"CANCEL_REAL_TIME_BARS",
		"REQ_FUNDAMENTAL_DATA",
		"CANCEL_FUNDAMENTAL_DATA",
		"REQ_CALC_IMPLIED_VOLAT",
		"REQ_CALC_OPTION_PRICE",
		"CANCEL_CALC_IMPLIED_VOLAT",
		"CANCEL_CALC_OPTION_PRICE",
		"REQ_GLOBAL_CANCEL",
		"REQ_MARKET_DATA_TYPE",
		"RequestPositions",
		"REQ_ACCOUNT_SUMMARY",
		"CANCEL_ACCOUNT_SUMMARY",
		"CancelPositions",
		"VERIFY_REQUEST",
		"VERIFY_MESSAGE",
		"QUERY_DISPLAY_GROUPS",
		"SUBSCRIBE_TO_GROUP_EVENTS",
		"UPDATE_DISPLAY_GROUP",
		"UNSUBSCRIBE_FROM_GROUP_EVENTS",
		"StartApi",
		"VERIFY_AND_AUTH_REQUEST",
		"VERIFY_AND_AUTH_MESSAGE",
		"REQ_POSITIONS_MULTI",
		"CANCEL_POSITIONS_MULTI",
		"RequestAccountUpdatesMulti",
		"CANCEL_ACCOUNT_UPDATES_MULTI",
		"REQ_SEC_DEF_OPT_PARAMS",
		"REQ_SOFT_DOLLAR_TIERS",
		"REQ_FAMILY_CODES",
		"REQ_MATCHING_SYMBOLS",
		"REQ_MKT_DEPTH_EXCHANGES",
		"REQ_SMART_COMPONENTS",
		"REQ_NEWS_ARTICLE",
		"REQ_NEWS_PROVIDERS",
		"REQ_HISTORICAL_NEWS",
		"REQ_HEAD_TIMESTAMP",
		"REQ_HISTOGRAM_DATA",
		"CANCEL_HISTOGRAM_DATA",
		"CANCEL_HEAD_TIMESTAMP",
		"REQ_MARKET_RULE",
		"REQ_PNL",
		"CANCEL_PNL",
		"REQ_PNL_SINGLE",
		"CANCEL_PNL_SINGLE",
		"REQ_HISTORICAL_TICKS",
		"REQ_TICK_BY_TICK_DATA",
		"CANCEL_TICK_BY_TICK_DATA"
	};

	inline string EWebReceiveString( EWebReceive value )
	{
		return (uint)value<sizeof(EWebReceiveStrings) ? string(EWebReceiveStrings[(uint)value]) : fmt::format( "Unknown value '{}'", (uint)value );
	}
}