#pragma once

namespace Jde::Markets::TwsWebSocket
{
	enum class EWebSend : int16
	{
		TickPrice                                = 1,
		TickSize                                 = 2,
		OrderStatus                              = 3,
		ErrorMessage                              = 4,
		OpenOrder                                = 5,
		ACCT_VALUE                                = 6,
		PORTFOLIO_VALUE                           = 7,
		ACCT_UPDATE_TIME                          = 8,
		NextValidId                               = 9,
		CONTRACT_DATA                             = 10,
		ExecutionData                             = 11,
		MARKET_DEPTH                              = 12,
		MARKET_DEPTH_L2                           = 13,
		NEWS_BULLETINS                            = 14,
		ManagedAccounts                           = 15,
		RECEIVE_FA                                = 16,
		HISTORICAL_DATA                           = 17,
		BOND_CONTRACT_DATA                        = 18,
		SCANNER_PARAMETERS                        = 19,
		SCANNER_DATA                              = 20,
		TICK_OPTION_COMPUTATION                   = 21,
		TickGeneric                               = 45,
		TickString                               = 46,
		TICK_EFP                                  = 47,
		CurrentTime                              = 49,
		RealTimeBars                            = 50,
		FUNDAMENTAL_DATA                          = 51,
		CONTRACT_DATA_END                         = 52,
		OPEN_ORDER_END                            = 53,
		ACCT_DOWNLOAD_END                         = 54,
		EXECUTION_DATA_END                        = 55,
		DELTA_NEUTRAL_VALIDATION                  = 56,
		TickSnapshotEnd                         = 57,
		MarketDataType                          = 58,
		COMMISSION_REPORT                         = 59,
		PositionData                             = 61,
		PositionEnd	                            = 62,
		ACCOUNT_SUMMARY                           = 63,
		ACCOUNT_SUMMARY_END                       = 64,
		VERIFY_MESSAGE_API                        = 65,
		VERIFY_COMPLETED                          = 66,
		DISPLAY_GROUP_LIST                        = 67,
		DISPLAY_GROUP_UPDATED                     = 68,
		VERIFY_AND_AUTH_MESSAGE_API               = 69,
		VERIFY_AND_AUTH_COMPLETED                 = 70,
		PositionMulti                            = 71,
		PositionMultiEnd                        = 72,
		AccountUpdateMulti                        = 73,
		ACCOUNT_UPDATE_MULTI_END                  = 74,
		SECURITY_DEFINITION_OPTION_PARAMETER      = 75,
		SECURITY_DEFINITION_OPTION_PARAMETER_END  = 76,
		SOFT_DOLLAR_TIERS                         = 77,
		FAMILY_CODES                              = 78,
		SYMBOL_SAMPLES                            = 79,
		MKT_DEPTH_EXCHANGES                       = 80,
		TickRequiredParams                        = 81,
		SMART_COMPONENTS                          = 82,
		NEWS_ARTICLE                              = 83,
		TICK_NEWS                                 = 84,
		NEWS_PROVIDERS                            = 85,
		HISTORICAL_NEWS                           = 86,
		HISTORICAL_NEWS_END                       = 87,
		HEAD_TIMESTAMP                            = 88,
		HISTOGRAM_DATA                            = 89,
		HISTORICAL_DATA_UPDATE                    = 90,
		REROUTE_MKT_DATA_REQ                      = 91,
		REROUTE_MKT_DEPTH_REQ                     = 92,
		MARKET_RULE                               = 93,
		PNL                                       = 94,
		PNL_SINGLE                                = 95,
		HISTORICAL_TICKS                          = 96,
		HISTORICAL_TICKS_BID_ASK                  = 97,
		HISTORICAL_TICKS_LAST                     = 98,
		TICK_BY_TICK                              = 99,

		Accept												= -1
	};

	constexpr std::string_view EWebSendStrings[]=
	{
		"0",
		"TickPrice","TickSize",
		"ORDER_STATUS",
		"ErrorMessage",
		"OPEN_ORDER",
		"ACCT_VALUE",
		"PORTFOLIO_VALUE",
		"ACCT_UPDATE_TIME",
		"NextValidId",
		"CONTRACT_DATA",
		"EXECUTION_DATA",
		"MARKET_DEPTH",
		"MARKET_DEPTH_L2",
		"NEWS_BULLETINS",
		"ManagedAccounts",
		"RECEIVE_FA",
		"HISTORICAL_DATA",
		"BOND_CONTRACT_DATA",
		"SCANNER_PARAMETERS",
		"SCANNER_DATA",
		"TICK_OPTION_COMPUTATION",
		"22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45",
		"TickGeneric",
		"TickString",
		"TICK_EFP",
		"CURRENT_TIME",
		"RealTimeBars",
		"FUNDAMENTAL_DATA",
		"CONTRACT_DATA_END",
		"OPEN_ORDER_END",
		"ACCT_DOWNLOAD_END",
		"EXECUTION_DATA_END",
		"DELTA_NEUTRAL_VALIDATION",
		"TickSnapshotEnd",
		"MarketDataType",
		"COMMISSION_REPORT",
		"POSITION_DATA",
		"POSITION_END",
		"ACCOUNT_SUMMARY",
		"ACCOUNT_SUMMARY_END",
		"VERIFY_MESSAGE_API",
		"VERIFY_COMPLETED",
		"DISPLAY_GROUP_LIST",
		"DISPLAY_GROUP_UPDATED",
		"VERIFY_AND_AUTH_MESSAGE_API",
		"VERIFY_AND_AUTH_COMPLETED",
		"POSITION_MULTI",
		"POSITION_MULTI_END",
		"ACCOUNT_UPDATE_MULTI",
		"ACCOUNT_UPDATE_MULTI_END",
		"SECURITY_DEFINITION_OPTION_PARAMETER",
		"SECURITY_DEFINITION_OPTION_PARAMETER_END",
		"SOFT_DOLLAR_TIERS",
		"FAMILY_CODES",
		"SYMBOL_SAMPLES",
		"MKT_DEPTH_EXCHANGES",
		"TickRequiredParams",
		"SMART_COMPONENTS",
		"NEWS_ARTICLE",
		"TICK_NEWS",
		"NEWS_PROVIDERS",
		"HISTORICAL_NEWS",
		"HISTORICAL_NEWS_END",
		"HEAD_TIMESTAMP",
		"HISTOGRAM_DATA",
		"HISTORICAL_DATA_UPDATE",
		"REROUTE_MKT_DATA_REQ",
		"REROUTE_MKT_DEPTH_REQ",
		"MARKET_RULE",
		"PNL",
		"PNL_SINGLE",
		"HISTORICAL_TICKS",
		"HISTORICAL_TICKS_BID_ASK",
		"HISTORICAL_TICKS_LAST",
		"TICK_BY_TICK"
	};

	inline string EWebSendString( EWebSend value )
	{
		return (uint)value<sizeof(EWebSendStrings) ? string(EWebSendStrings[(uint)value]) : fmt::format( "Unknown value '{}'", (uint)value );
	}
}